export const BUS_DATA = [
  {
    id: 1,
    line: "YBS 1",
    startTerm: "Htauk Kyant",
    endTerm: "Sule Pagoda",
  },
  {
    id: 2,
    line: "YBS 4",
    startTerm: "South Dagon (Roundabout)",
    endTerm: "Pazundaung Market",
  },
  {
    id: 3,
    line: "YBS 7",
    startTerm: "Hlegu",
    endTerm: "Sule Pagoda",
  },
  {
    id: 4,
    line: "YBS 11",
    startTerm: "Mingaladon (Airport Rd)",
    endTerm: "Thakin Mya Park",
  },
  {
    id: 5,
    line: "YBS 12",
    startTerm: "Dagon University",
    endTerm: "Sule Pagoda",
  },
  {
    id: 6,
    line: "YBS 21",
    startTerm: "Insein (CID)",
    endTerm: "Botahtaung Pagoda",
  },
  {
    id: 7,
    line: "YBS 29",
    startTerm: "North Okkalapa (Thudamar)",
    endTerm: "Theingyi Zay",
  },
  {
    id: 8,
    line: "YBS 35",
    startTerm: "Hlaing Tharyar (Aung Zeya)",
    endTerm: "Sule Pagoda",
  },
  {
    id: 9,
    line: "YBS 36",
    startTerm: "Htauk Kyant",
    endTerm: "Sule Pagoda",
  },
  {
    id: 10,
    line: "YBS 37",
    startTerm: "Hlaing Tharyar (Aung Zeya)",
    endTerm: "Mawtin Jetty",
  },
  {
    id: 11,
    line: "YBS 39",
    startTerm: "Insein (CID)",
    endTerm: "Sule Pagoda",
  },
  {
    id: 12,
    line: "YBS 56",
    startTerm: "North Okkalapa",
    endTerm: "Theingyi Zay",
  },
  {
    id: 13,
    line: "YBS 58",
    startTerm: "Mingaladon (Zaykabar)",
    endTerm: "Sule Pagoda",
  },
  {
    id: 14,
    line: "YBS 61",
    startTerm: "Insein (Danyingone)",
    endTerm: "Thaketa (Shwe Pauk Kan)",
  },
  {
    id: 15,
    line: "YBS 65",
    startTerm: "Dagon University",
    endTerm: "Thaketa Roundabout",
  },
  {
    id: 16,
    line: "YBS 78",
    startTerm: "Shwepyitha (Danyingone)",
    endTerm: "Mawtin Jetty",
  },
  {
    id: 17,
    line: "YBS 89",
    startTerm: "Shwepyitha (Nawaday)",
    endTerm: "Sule Shangri-La",
  },
  {
    id: 18,
    line: "YBS 102",
    startTerm: "Yangon International Airport (T1)",
    endTerm: "Yangon Central Railway Station",
  },
];